### ISSUE TITLE
not get the right result

### ISSUE THREAD

**Issue by 15thai** [RafaelNH/gibbs-removal#5]
Hi. I tried your code version, and somehow, it got strange results.
here is the input:

![image](https://user-images.githubusercontent.com/18472072/59135499-19cf1680-894d-11e9-96fc-ecb8941a9d35.png)

and here is the output
![image](https://user-images.githubusercontent.com/18472072/59135384-b8a74300-894c-11e9-8cbe-f94ce53cb75d.png)

as I kept everything as default. the size of the image is 192x192x110. 
Let me know if I missed anything. Thank you.

**Comment by RafaelNH** [comment]
Hi @15thai! Thanks for pointing this out! I will give a look. In meantime you can use the version that I am implementing for dipy PR[#1771](https://github.com/nipy/dipy/pull/1771)

**Comment by 15thai** [comment]
Hi, @RafaelNH I did try the version in your PR [https://github.com/RafaelNH/dipy/blob/Gibbs_Removal/dipy/denoise/gibbs.py](https://github.com/RafaelNH/dipy/blob/Gibbs_Removal/dipy/denoise/gibbs.py). The result is still the same.

**Comment by RafaelNH** [comment]
Hi @15thai! I did a major revision on this code. I am not detecting this issue on the data that I've tested the code. Please see [Gibbs suppression example](https://github.com/RafaelNH/gibbs-removal/blob/master/GIBBSremoval_example.ipynb). Can you share this dataset?
